"""added external_id column

Revision ID: 58e29329f9c0
Revises: 2f9ae8abbd7d
Create Date: 2021-01-30 13:57:34.256803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e29329f9c0'
down_revision = '2f9ae8abbd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('external_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'external_id')
    # ### end Alembic commands ###
