"""empty message

Revision ID: 226944278c11
Revises: 37b1ad5fcef2
Create Date: 2021-02-09 17:06:41.590803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226944278c11'
down_revision = '37b1ad5fcef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'roles')
    op.drop_column('user', 'password')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('roles', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
