"""empty message

Revision ID: 230aeeaa6812
Revises: 
Create Date: 2021-02-04 19:56:58.156667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230aeeaa6812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('carbohydrate', sa.Integer(), nullable=True))
    op.add_column('meal', sa.Column('fiber', sa.Integer(), nullable=True))
    op.drop_column('meal', 'carb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('carb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('meal', 'fiber')
    op.drop_column('meal', 'carbohydrate')
    # ### end Alembic commands ###
