"""empty message

Revision ID: 37b1ad5fcef2
Revises: 1902ec530665
Create Date: 2021-02-05 12:45:40.959407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b1ad5fcef2'
down_revision = '1902ec530665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
