"""external_id must be unique

Revision ID: 7227762b976d
Revises: 58e29329f9c0
Create Date: 2021-01-30 14:02:28.025446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7227762b976d'
down_revision = '58e29329f9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'foods', ['external_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foods', type_='unique')
    # ### end Alembic commands ###
