"""empty message

Revision ID: 84587bfccbdf
Revises: 230aeeaa6812
Create Date: 2021-02-04 20:08:22.704683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84587bfccbdf'
down_revision = '230aeeaa6812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal', 'food_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meal', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meal', 'food_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
