"""empty message

Revision ID: fd12091fa9d7
Revises: 84587bfccbdf
Create Date: 2021-02-05 12:26:50.119196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd12091fa9d7'
down_revision = '84587bfccbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('image', sa.String(), nullable=False))
    op.add_column('food', sa.Column('quantity', sa.Float(), nullable=False))
    op.add_column('meal', sa.Column('image', sa.String(), nullable=False))
    op.add_column('meal', sa.Column('quantity', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'quantity')
    op.drop_column('meal', 'image')
    op.drop_column('food', 'quantity')
    op.drop_column('food', 'image')
    # ### end Alembic commands ###
