branch-defaults:
  default:
    environment: range-dev
    group_suffix: null
environment-defaults:
  range-dev:
    branch: null
    repository: null
global:
  application_name: range
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
